services:
  math-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: math-app
    restart: unless-stopped

    # Переменные окружения
    environment:
      - NODE_ENV=production
      - PORT=3000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ADMIN_TOKEN=${ADMIN_TOKEN}

    # Порты
    ports:
      - "3000:3000"

    # Volumes для сохранения данных
    volumes:
      # База данных и загруженные файлы
      - ./data/database:/app/database
      # Публичные изображения
      - ./data/public-images:/app/public/images
      # Временные файлы
      - ./data/temp:/app/temp

    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Логирование
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # Ограничения ресурсов (опционально)
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 512M
    #     reservations:
    #       cpus: '0.5'
    #       memory: 256M

# Named volumes для лучшего управления (альтернатива bind mounts)
# volumes:
#   database_data:
#   public_images:
#   temp_data:
